" set numbring
	set number relativenumber
	set nuw=3
	set tabstop=4
" basic settings
	set nocompatible
	set backspace=indent,eol,start
	set encoding=utf-8
	syntax on
	scriptencoding utf-8
	setglobal fileencoding=utf-8

" enable autocompletion 
	set wildmode=longest,list,full
	

" enable easier split nativagation 
	map <C-h> <C-w>h
	map <C-j> <C-w>j
	map <C-k> <C-w>k
	map <C-l> <C-w>l
